= Extract yaml

ID[REQ::Extract_yaml]

== From any file

ID[::read_any_file]

== Alligned to yaml syntax

ID[::syntax]

== Performance

ID[::performance, required: optional]

It could make sense to have to kinds of syntactical options.

=== Bracket

ID[::performance::syntax_bracket]

==== Example evaluated

All proper yaml is allowed

```
ID#[test, content: [A, "]]]}{[[]}}"]]
```

=== Closure

ID[::performance::syntax_closure]


==== Example unevaluated

Everything according to yaml, exept the chars '{' and '}' is allowd.

Allowed:

```
ID#{test, content: [A, "]]]"]}
```

Not allowed:

```
ID#{test, content: [{A: abc}, "{} }"]}
```


== Ignore comment tags

ID[::multiline_comment]

To ignore multiline comments like #, //, /* at the beginning of a line within a ID.

(Add to IMPL:)
This could be done via ignoring the first word before the word before ":".

== Provide reasonable performace

ID[::benchmarking]

To check the performance of the curt tooling provide benchmarks of elementary functions.

Functions::
- cut-yaml
- cut-yaml-idents
