on: [pull_request]
name: Benchmarks
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: "Checkout sources"
      - uses: actions-rs/toolchain@v1
        name: "Setup rust toolchain"
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        name: "Measure benchmark changes"
        with:
          command: bench
          args: --bench benchmark -- --save-baseline changes
      - uses: actions/checkout@v1
        name: "Checkout master sources"
        with:
          ref: master
      - uses: actions-rs/cargo@v1
        name: "Measure benchmark master"
        with:
          command: bench
          args: --bench benchmark -- --save-baseline master
      - uses: jsqu4re/criterion-compare-action@master
        name: "Compare benchmarks"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
