on: [pull_request]
name: Benchmarks
jobs:
  runBenchmark:
    name: run benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: "Checkout sources"
      - uses: actions-rs/toolchain@v1
        name: "Setup rust toolchain"
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: jsqu4re/criterion-compare-action@v1.0.5
        name: "Compare benchmarks"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
