name: Rust

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        rust:
          - stable
          - beta
          - nightly
          # - 1.31.0  # MSRV

    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: true
        components: rustfmt, clippy

    - uses: actions-rs/cargo@v1
      with:
        command: build

    - uses: actions-rs/cargo@v1
      with:
        command: test

    - uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings
