name: "Rust Build Pipeline"

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        rust:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v1
      name: "Checkout sources"
    - uses: actions-rs/toolchain@v1
      name: "Setup rust toolchain"
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
        override: "true"
        components: rustfmt, clippy

    - uses: actions-rs/cargo@v1
      name: "Cargo build"
      with:
        command: build

    - uses: actions-rs/cargo@v1
      name: "Cargo test"
      with:
        command: test

    - uses: actions-rs/cargo@v1
      name: "Fmt checks"
      with:
        command: fmt
        args: --all -- --check

    - uses: actions-rs/cargo@v1
      name: "Clippy checks"
      with:
        command: clippy
        args: -- -D warnings
